process CAREAMICS_CONFIG {
    tag "$meta.id"
    label 'process_single'

    conda "${moduleDir}/environment.yml"
    container // Add in Apptainer generated by Tatiana

    input:
    tuple val(meta), path(dataset_dir)    
    val(config_file_name)              
    val(algorithm)                       // Algorithm to configure (N2V, CARE, etc.)
    val(output_dir)                     
    val(params_map)                      

    output:
    tuple val(meta), path("${config_file_name}.yaml"), emit: config  // Generated config file
    path "versions.yml", emit: versions                             // Software version info

    script:
    """
    careamics config \\
        --data ${dataset_dir} \\
        --results ${output_dir} \\
        --algorithm ${algorithm} \\
        ${params_map.collect { key, value -> "--${key} ${value}" }.join(' ')} \\
        --config ${config_file_name}.yaml

    # Record of software version
    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        careamics: \$(careamics --version |& head -n 1 | awk '{print \$NF}')
    END_VERSIONS
    """
}
