---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "careamics_config"
description: "Generates a configuration file for Careamics to be used for training and prediction in image restoration workflows."
keywords:
  - careamics
  - image-processing
  - image restoration
  - microscopy
  - deep-learning
tools:
  - "careamics":
      description: "Careamics is a deep learning-based image restoration library for microscopy data."
      homepage: "https://careamics.github.io"
      documentation: "https://github.com/CAREamics/careamics/releases/tag/v0.0.4.2"
      tool_dev_url: "https://github.com/CAREamics/careamics"
      doi: #tbd
      licence: "BSD 3-Clause"
      identifier: "careamics:config"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information.
        (sample id) #fix
  - dataset_dir:
      type: directory
      description: "Path to the dataset directory containing input images."
  - config_file_name:
      type: string
      description: "Name of the output configuration file."
  - algorithm:
      type: string
      description: "Algorithm to configure (e.g., Noise2Void or CARE)."
  - output_dir:
      type: directory
      description: "Directory to save the generated configuration and results."
  - params_map:
      type: map
      description: |
        Dictionary of additional parameters specific to the algorithm.
        Example: `{ 'patch_size': 64, 'batch_size': 32 }`

output:
  - config:
      type: file
      description: "Generated configuration file for the specified Careamics algorithm."
      pattern: "*.yaml"
     
  - versions:
      type: file
      description: "File containing the versions of the software used in the module."
      pattern: "versions.yml"

authors:
  - "@diyasrivas"
  - "@melisande-c"
maintainers:
  - "@diyasrivas"
  - "@melisande-c"
